# Generated by Django 3.2.3 on 2023-09-16 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_ingridient'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingridient',
            new_name='Ingredient',
        ),
    ]
