# Generated by Django 3.2.3 on 2023-09-25 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_receipt_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiptingredient',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_ingredient', to='recipes.receipt'),
        ),
    ]
