# Generated by Django 3.2.3 on 2023-09-28 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_auto_20230927_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='image',
            field=models.ImageField(upload_to='images/recipes/', verbose_name='Картинка'),
        ),
    ]
